### ISSUE TITLE
Mod not working on new Android geode update (Geode v1.4.2)

### ISSUE THREAD

**Issue by C0d1ngR4bb1t** [nightmoonv/Click-Between-Frames-Android#1]
Error image:
![Screenshot_20241213_094124_Geode](https://github.com/user-attachments/assets/144fc947-3324-4599-9e2d-51406afb25c9)

**Comment by C0d1ngR4bb1t** [comment]
Just fixed it with ChatGPT and it works. I'll attach the working mod.json file
[mod.json](https://github.com/user-attachments/files/18136905/mod.json)

**Comment by nightmoonv** [comment]
Dont use the file adder use zarchiver

**Comment by C0d1ngR4bb1t** [comment]
The bufgix you have released doesn't work (even when being imported using zarchiver (by moving files))
